// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_aricle_by_id.sql

package sqlc

import (
	"context"
)

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, content, created_at
FROM articles
WHERE id = $1
`

func (q *Queries) GetArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
