// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int64
	Title     string
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Category struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}
